In [1]:
import numpy as np

In [6]:
#creating a 1D Array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [10]:
#creating a 2D Array
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)
print(type(arr2))
print(arr2.shape) #2D array with 3 rows and 3 columns

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
(3, 3)


In [11]:
arr3 = np.array([1,2,3,4,5])
arr3 = arr3.reshape(1,5)
print(arr3)
print(arr3.shape)


[[1 2 3 4 5]]
(1, 5)


In [12]:
np.arange(1,10) #creating an array with a range of values from 1 to 9

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.ones((3,4)) #creates a 2D array with 3 rows and 4 columns filled with ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [22]:
#Numpy Vectorized operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

print("Addition:", arr1 + arr2) #elements present in the same index are added together

Addition: [11 22 33 44 55]


In [23]:
#performing SQRT operation
arr = np.array([1,4,9,16,25])
print("Square root:", np.sqrt(arr)) #calculates the square root of each element in the array


Square root: [1. 2. 3. 4. 5.]


In [25]:
#slicing and indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [37]:
print(arr[1:, 2:4])
print(arr[0:2,2:4])

[[ 7  8]
 [11 12]]
[[3 4]
 [7 8]]


In [38]:
#statistical concept - data normalization
#to have a mean of 0 and standard deviation of 1
data = np.array([10,20,30,40,50])
normalized_data = (data - np.mean(data)) / np.std(data)
print("Normalized Data:", normalized_data)

Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
